/**
 * robots.txt, generated by Next's metadata route.
 *
 * P-07. The storefront had no robots.txt and no sitemap at all — both 404'd in
 * production. That undercut the rest of the SEO work: the catalogue is rendered
 * server-side specifically so a crawler can read it, every page sets a
 * canonical, and the PDP ships Product + BreadcrumbList JSON-LD. None of that
 * helps a crawler that is never told what to fetch or which paths to leave
 * alone.
 *
 * The disallow list is the set of paths that are either per-customer (so a
 * crawler sees only a redirect to /login) or transactional. Leaving them
 * crawlable spends crawl budget on pages that can never rank and risks
 * order-confirmation and tracking URLs surfacing in search.
 */

import { siteUrl } from '@/lib/site-url';

export default function robots() {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/cart',
          '/checkout',
          '/profile',
          '/orders/',
          '/order-confirmation/',
          '/appointments',
          '/wishlist',
          '/compare',
          '/notifications',
          '/login',
          '/signup',
          '/forgot-password',
          '/reset-password',
        ],
      },
    ],
    sitemap: `${siteUrl()}/sitemap.xml`,
    host: siteUrl(),
  };
}
