import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsArray,
  IsBoolean,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  Min,
  MinLength,
} from 'class-validator';

/**
 * Payload for creating a product (admin only). Mirrors the `products` table;
 * `search_tsv` is generated by the database and never accepted here.
 */
export class CreateProductDto {
  @ApiProperty({ description: 'Stock-keeping unit (unique)', example: 'OPX-RB-0001' })
  @IsString()
  @MinLength(1)
  @MaxLength(64)
  sku!: string;

  @ApiProperty({ description: 'URL slug (unique)', example: 'ray-ban-aviator-classic' })
  @IsString()
  @MinLength(1)
  @MaxLength(160)
  slug!: string;

  @ApiProperty({ description: 'Display name', example: 'Ray-Ban Aviator Classic' })
  @IsString()
  @MinLength(1)
  name!: string;

  @ApiProperty({ description: 'Category UUID' })
  @IsUUID()
  category_id!: string;

  @ApiPropertyOptional({ description: 'Brand name' })
  @IsString()
  @IsOptional()
  brand?: string;

  @ApiPropertyOptional({ description: 'Frame material' })
  @IsString()
  @IsOptional()
  frame_material?: string;

  @ApiPropertyOptional({
    description: 'Frame shape (round, square, aviator, cat-eye, ...)',
  })
  @IsString()
  @IsOptional()
  frame_shape?: string;

  @ApiPropertyOptional({ description: 'Gender (men, women, unisex, kids)' })
  @IsString()
  @IsOptional()
  gender?: string;

  @ApiPropertyOptional({ description: 'Long-form description' })
  @IsString()
  @IsOptional()
  description?: string;

  @ApiProperty({ description: 'Price in KES', example: 12500, minimum: 0 })
  @IsNumber()
  @Min(0)
  price_kes!: number;

  @ApiPropertyOptional({
    description: 'Gallery image URLs',
    type: [String],
    default: [],
  })
  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  images?: string[];

  @ApiPropertyOptional({ description: 'Transparent try-on PNG URL (Phase 3)' })
  @IsString()
  @IsOptional()
  try_on_image_url?: string;

  @ApiPropertyOptional({
    description: 'Whether the product is active/visible',
    default: true,
  })
  @IsBoolean()
  @IsOptional()
  is_active?: boolean;
}
